In [1]:
import numpy as np

In [7]:
s=np.array([[1,1,1,1],[2,2,2,2],[1,1,1,4],[1,1,1,9]], dtype=np.int16)

In [3]:
np.sqrt(s)

array([[3.4641016, 1.7320508, 2.828427 , 2.236068 ],
       [4.690416 , 1.       , 3.4641016, 3.       ],
       [0.       , 2.236068 , 1.       , 6.6332498],
       [1.       , 1.       , 1.       , 3.       ]], dtype=float32)

In [4]:
s-s

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [9]:
s.sum(axis=1, keepdims=True)

array([[ 4],
       [ 8],
       [ 7],
       [12]])

In [8]:
s

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [1, 1, 1, 4],
       [1, 1, 1, 9]], dtype=int16)